#!/usr/bin/env bash
#
# fix-earlyoom.sh
#
# Installs and configures earlyoom to kill runaway processes before the system
# freezes under memory pressure. Without earlyoom (or systemd-oomd), Linux will
# thrash swap and lock up completely — requiring a hard power-off.
#
# earlyoom monitors available memory and swap in userspace, sending SIGTERM
# (then SIGKILL) to the highest-scoring process before the kernel OOM path
# is reached. This keeps the system responsive even during memory spikes.
#
# Fixes applied:
#   1. Installs earlyoom via dnf
#   2. Configures thresholds and process preferences
#   3. Enables desktop notifications (optional)
#   4. Disables systemd-oomd to avoid conflicts
#   5. Enables and starts the earlyoom service
#
# Usage:
#   sudo ./fix-earlyoom.sh [OPTIONS]
#
# Options:
#   --mem-thresh PERCENT     SIGTERM when free RAM falls below this (default: 15)
#   --swap-thresh PERCENT    SIGTERM when free swap falls below this (default: 10)
#   --notify                 Enable desktop kill notifications via D-Bus
#   --dry-run                Show what would be done without making changes
#   --help                   Show this help message

set -euo pipefail

# Defaults
MEM_THRESH=15
SWAP_THRESH=10
NOTIFY=false
DRY_RUN=false
CONFIG_FILE="/etc/default/earlyoom"

# Processes to protect (never kill these)
AVOID_REGEX='(^|/)(init|systemd|sshd|dockerd|containerd|gnome-shell|Xorg|Xwayland|plasmashell|pipewire|wireplumber)$'

# Processes to kill first (heavy, disposable, or easily restarted)
PREFER_REGEX='(^|/)(Web Content|firefox-bin|chrome|chromium|electron|node|java|bundle)$'

usage() {
    sed -n '/^# Usage:/,/^$/p' "$0" | sed 's/^# \?//'
    exit 0
}

log() { echo "[*] $*"; }
warn() { echo "[!] $*" >&2; }
dry() { echo "[dry-run] $*"; }

parse_args() {
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --mem-thresh)   MEM_THRESH="$2"; shift 2 ;;
            --swap-thresh)  SWAP_THRESH="$2"; shift 2 ;;
            --notify)       NOTIFY=true; shift ;;
            --dry-run)      DRY_RUN=true; shift ;;
            --help)         usage ;;
            *) warn "Unknown option: $1"; usage ;;
        esac
    done

    if [[ "$MEM_THRESH" -lt 1 || "$MEM_THRESH" -gt 50 ]]; then
        warn "Memory threshold must be between 1 and 50"
        exit 1
    fi
    if [[ "$SWAP_THRESH" -lt 1 || "$SWAP_THRESH" -gt 50 ]]; then
        warn "Swap threshold must be between 1 and 50"
        exit 1
    fi
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        warn "This script must be run as root (sudo)."
        exit 1
    fi
}

install_earlyoom() {
    if command -v earlyoom &>/dev/null; then
        log "earlyoom is already installed."
        return
    fi

    log "Installing earlyoom..."

    if $DRY_RUN; then
        dry "dnf install -y earlyoom"
        return
    fi

    dnf install -y earlyoom
    log "earlyoom installed."
}

configure_earlyoom() {
    log "Configuring earlyoom (mem=${MEM_THRESH}%, swap=${SWAP_THRESH}%)..."

    # SIGKILL threshold is half the SIGTERM threshold
    local mem_kill=$(( MEM_THRESH / 2 ))
    local swap_kill=$(( SWAP_THRESH / 2 ))

    local args="-m ${MEM_THRESH},${mem_kill} -s ${SWAP_THRESH},${swap_kill}"
    args+=" --avoid '${AVOID_REGEX}'"
    args+=" --prefer '${PREFER_REGEX}'"

    if $NOTIFY; then
        args+=" -n"
    fi

    local config_line="EARLYOOM_ARGS=\"${args}\""

    if $DRY_RUN; then
        dry "Write to ${CONFIG_FILE}:"
        dry "  ${config_line}"
        return
    fi

    # Back up existing config
    if [[ -f "$CONFIG_FILE" ]]; then
        cp "$CONFIG_FILE" "${CONFIG_FILE}.bak"
        log "Backed up existing config to ${CONFIG_FILE}.bak"
    fi

    cat > "$CONFIG_FILE" <<EOF
# earlyoom configuration
# Generated by fix-earlyoom.sh on $(date -I)
#
# Thresholds: SIGTERM at ${MEM_THRESH}% free RAM / ${SWAP_THRESH}% free swap
#             SIGKILL at ${mem_kill}% free RAM / ${swap_kill}% free swap
#
# Both memory AND swap must fall below their thresholds for earlyoom to act.
${config_line}
EOF

    log "Configuration written to ${CONFIG_FILE}."
}

disable_oomd() {
    # systemd-oomd conflicts with earlyoom — both try to kill under pressure
    if systemctl is-active --quiet systemd-oomd 2>/dev/null; then
        log "Disabling systemd-oomd to avoid conflicts..."

        if $DRY_RUN; then
            dry "systemctl disable --now systemd-oomd"
            return
        fi

        systemctl disable --now systemd-oomd
        log "systemd-oomd disabled."
    else
        log "systemd-oomd is not active. Nothing to disable."
    fi
}

enable_earlyoom() {
    log "Enabling and starting earlyoom service..."

    if $DRY_RUN; then
        dry "systemctl enable --now earlyoom"
        return
    fi

    systemctl enable --now earlyoom
    log "earlyoom service is active."
}

show_summary() {
    echo ""
    log "Summary:"
    echo "    Service:     $(systemctl is-active earlyoom 2>/dev/null || echo 'unknown')"
    echo "    Config:      ${CONFIG_FILE}"
    echo "    Mem thresh:  SIGTERM at ${MEM_THRESH}% free, SIGKILL at $(( MEM_THRESH / 2 ))% free"
    echo "    Swap thresh: SIGTERM at ${SWAP_THRESH}% free, SIGKILL at $(( SWAP_THRESH / 2 ))% free"
    echo "    Total RAM:   $(free -h | awk '/^Mem:/ {print $2}')"
    echo "    Total Swap:  $(free -h | awk '/^Swap:/ {print $2}')"
    echo ""
    log "Done. earlyoom will now kill the heaviest process before the system freezes."
    log "Check logs with: journalctl -u earlyoom"
}

main() {
    parse_args "$@"
    check_root
    install_earlyoom
    configure_earlyoom
    disable_oomd
    enable_earlyoom

    if $DRY_RUN; then
        echo ""
        log "Dry run complete. No changes were made."
    else
        show_summary
    fi
}

main "$@"
